<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DpohDf5' shared service.

return $this->privates['.service_locator.DpohDf5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ArticleController::createAction' => ['privates', '.service_locator.NUP9Hmn', 'get_ServiceLocator_NUP9HmnService.php', true],
    'App\\Controller\\ArticleController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\ArticleController:createAction' => ['privates', '.service_locator.NUP9Hmn', 'get_ServiceLocator_NUP9HmnService.php', true],
    'App\\Controller\\ArticleController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\ArticleController::createAction' => '?',
    'App\\Controller\\ArticleController::setViewHandler' => '?',
    'App\\Controller\\ArticleController:createAction' => '?',
    'App\\Controller\\ArticleController:setViewHandler' => '?',
]);
