<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnAaZl6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnAaZl6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKnAaZl6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKnAaZl6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKnAaZl6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KnAaZl6',
    'container.build_id' => '4160faa7',
    'container.build_time' => 1574727694,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnAaZl6');
